version: '3'
services:
  redis-node-0:
    build:
      context: ../
      dockerfile: ./build/RedisClusterDockerfile
    image: redis-cluster:6.2.1-alpine
    networks:
      podium:
        aliases:
          - redis-node-0
  redis-node-1:
    build:
      context: ../
      dockerfile: ./build/RedisClusterDockerfile
    image: redis-cluster:6.2.1-alpine
    networks:
      podium:
        aliases:
          - redis-node-1
  redis-node-2:
    build:
      context: ../
      dockerfile: ./build/RedisClusterDockerfile
    image: redis-cluster:6.2.1-alpine
    networks:
      podium:
        aliases:
          - redis-node-2

  initialize-cluster:
    build:
      context: ../
      dockerfile: ./build/InitializeRedisClusterDockerfile
    image: initialize-redis-cluster:6.2.1-alpine
    environment:
      - "CLUSTER_HOSTS=redis-node-0:6379 redis-node-1:6379 redis-node-2:6379"
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
    networks:
      - podium

  redis-standalone:
    image: redis:6.2.1-alpine
    networks:
      podium:
        aliases:
          - redis-standalone

  podium-test:
    build:
      context: ../
      dockerfile: ./build/TestAppDockerfile
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-standalone
    environment:
      - "PODIUM_REDIS_HOST=redis-standalone"
    volumes:
      - "../:/podium"
      - "/Users/arthur.nogueira/.asdf/installs/golang/1.15.2/packages/pkg/mod:/go/pkg/mod"
    networks:
      - podium

networks:
  podium:
