language: go

go:
  - 1.6.2

sudo: required

services:
  - docker
  - redis-server

install:
  - go get github.com/mattn/goveralls
  - make setup

script:
  - make test-coverage

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile _build/test-coverage-all.out -service=travis-ci
  - make cross-linux
  - ./scripts/push_to_docker.sh
  - curl -H POST $TEST_FARM_URL
